### ISSUE TITLE
Animation in matplotlib

### ISSUE THREAD

**Issue by starboy007-debug** [starboy007-debug/Matplotlib-seaborn#1]
I tried to animate the dataset but failed if anyone could solve it will be helpful

**Comment by TheBlckCat** [comment]
Hi ✌️, I want to work on this issue

**Comment by starboy007-debug** [comment]
yes sure it will be helpful

**Comment by TheBlckCat** [comment]
%matplotlib notebook
from matplotlib import animation

fig = plt.figure()
ax1 = plt.subplot(111)
line, = ax1.plot([],[])

ax1.set_xlim(0,2)
ax1.set_ylim(-1.5,1.5)

def init():
    ax1.set_xlabel('x')
    ax1.set_ylabel('sin(x)')
    ax1.set_title('sin curve')
    line.set_data([],[])
    return line,

def animate(i):
    x = np.linspace(0,2,1000)
    y = np.sin(2*np.pi*(x-0.01*i))
    line.set_data(x,y)
    return line,

anim = animation.FuncAnimation(fig, animate, init_func=init, frames=100, interval=100, blit=True, repeat=True)

plt.show()

anim.save('basic_animation.mp4', fps=30)

**Comment by starboy007-debug** [comment]
thanx a lot
